<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="myCNC_JobQue" Id="{6e28ccc1-17ae-4824-a263-0971fb095314}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM myCNC_JobQue
VAR

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="myCNC_JobQue">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>