<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="myParts" Id="{644fb9b2-df71-440f-9e4f-905e2e095be0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM myParts
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	]]></ST>
    </Implementation>
    <LineIds Name="myParts">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>