<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_ArmsInLoadOrientation" Id="{da158143-06ca-441d-bcfe-88e196ad8603}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ArmsInLoadOrientation : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="F_ArmsInLoadOrientation">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>